# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  username:
    required: true
    description: "Steam username"
    default: 'username-null'
  password:
    required: true
    default: 'password-null'
    description: "Steam password"
outputs:
  time: # id of output
    description: 'The time we greeted you'
  username: # id of output
    description: 'The username'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}

